#include "gpio.h"
#include "pins.h"

#define INIT_PORT_OUT(PORT,PIN) HAL_GPIO_WritePin(PORT,PIN,GPIO_PIN_RESET);\
                                GPIO_InitStruct.Pin = PIN;\
                                GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;\
                                GPIO_InitStruct.Pull = GPIO_NOPULL;\
                                GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;\
                                HAL_GPIO_Init(PORT, &GPIO_InitStruct);

void MX_GPIO_Init(void)
{

GPIO_InitTypeDef GPIO_InitStruct;

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();	
  __HAL_RCC_GPIOE_CLK_ENABLE();
  __HAL_RCC_GPIOF_CLK_ENABLE();
  __HAL_RCC_GPIOG_CLK_ENABLE();
  
  INIT_PORT_OUT(MON_POWER_PORT,MON_POWER_PIN);         //Питание монитора

  INIT_PORT_OUT(PRINTER_POWER_PORT,PRINTER_POWER_PIN); //PRINTER POWER
  INIT_PORT_OUT(SDIO_POWER_PORT,SDIO_POWER_PIN);       //SD-card Power
  INIT_PORT_OUT(CHARGE_ENABLE_PORT,CHARGE_ENABLE_PIN); //Разрешение заряда

  BAT_ENABLE(1);                                       //Разрешение батарейного питания
  GPIO_InitStruct.Pin = BAT_ENABLE_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_OD;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(BAT_ENABLE_PORT, &GPIO_InitStruct);

  //Дополнительные выходы питания
  INIT_PORT_OUT(OTHER_PSO1_PORT,OTHER_PSO1_PIN);
  INIT_PORT_OUT(OTHER_PSO2_PORT,OTHER_PSO2_PIN);
  INIT_PORT_OUT(OTHER_PSO3_PORT,OTHER_PSO3_PIN);

  INIT_PORT_OUT(CARD_READER_PORT,CARD_READER_PIN);     //CARD READER POWER
  INIT_PORT_OUT(LOCK_PSO_PORT,LOCK_PSO_PIN);           //Замок


//  INIT_PORT_OUT(SPKR_PORT,SPKR_PIN);

  GPIO_InitStruct.Pin = SPKR_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  GPIO_InitStruct.Alternate = GPIO_AF2_TIM3;
  HAL_GPIO_Init(SPKR_PORT, &GPIO_InitStruct);

//  GPIO_InitStruct.Pin = SPKR_PIN;
//  GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
//  GPIO_InitStruct.Pull = GPIO_NOPULL;
//  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
//  GPIO_InitStruct.Alternate = GPIO_AF2_TIM4;
//  HAL_GPIO_Init(SPKR_PORT, &GPIO_InitStruct);

//############################################################
  INIT_PORT_OUT(MONITOR_BUTTON_PORT,MONITOR_BUTTON_PIN); //Кнопка включения монитора

//Светодиоды
  INIT_PORT_OUT(LED1_PORT,LED1_PIN);
  INIT_PORT_OUT(LED2_PORT,LED2_PIN);
  INIT_PORT_OUT(LED3_PORT,LED3_PIN);
  INIT_PORT_OUT(LED4_PORT,LED4_PIN);
  INIT_PORT_OUT(LED5_PORT,LED5_PIN);
  INIT_PORT_OUT(LED6_PORT,LED6_PIN);
  INIT_PORT_OUT(LED7_PORT,LED7_PIN);
  INIT_PORT_OUT(LED8_PORT,LED8_PIN);
  INIT_PORT_OUT(LED9_PORT,LED9_PIN);
  INIT_PORT_OUT(LED10_PORT,LED10_PIN);
  INIT_PORT_OUT(LED11_PORT,LED11_PIN);
  INIT_PORT_OUT(LED12_PORT,LED12_PIN);
  INIT_PORT_OUT(LED13_PORT,LED13_PIN);
  INIT_PORT_OUT(LED14_PORT,LED14_PIN);
  INIT_PORT_OUT(LED15_PORT,LED15_PIN);
  INIT_PORT_OUT(LED16_PORT,LED16_PIN);
  INIT_PORT_OUT(POWER_LED_PORT,POWER_LED_PIN);

  SDIO_POWER_OFF;
  GPIO_InitStruct.Pin = SDIO_PSO_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(SDIO_PSO_PORT, &GPIO_InitStruct);
  SDIO_POWER_OFF;

  INIT_PORT_OUT(LED_ERROR_PORT,LED_ERROR_PIN);
  INIT_PORT_OUT(LED_OK_PORT,LED_OK_PIN);

  INIT_PORT_OUT(LED_HOPPER_PORT,LED_HOPPER_PIN);
  INIT_PORT_OUT(LED_PRINTER_PORT,LED_PRINTER_PIN);

  INIT_PORT_OUT(RESERVE_POWER_PORT,RESERVE_POWER_PIN);
  INIT_PORT_OUT(VALIDATOR_ON_PORT,VALIDATOR_ON_PIN);
  INIT_PORT_OUT(STATUS_LED_PORT,STATUS_LED_PIN);

  INIT_PORT_OUT(USB_POWER_PORT,USB_POWER_PIN);
  USB_POWER(0);
}
